package:
  name: tonic
  version: "0.13.1"

source:
  fn: tonic-0.13.1.tar.gz
  url: https://pypi.python.org/packages/source/p/tonic/tonic-0.13.1.tar.gz
  md5: e347036acc50720c0903dc2221b2605d
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pyinstrument = pyinstrument:main
    #
    # Would create an entry point called pyinstrument that calls pyinstrument.main()

    - tonic = tonic.__main__:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - tonic

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - tonic --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/joerick/pyinstrument
  license: BSD License
  summary: "A tool kit for processing hydrologic models in Python."

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
